CRUD-7/CRUD7/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("task/",views.task),
    path("show/",views.show),
    path("edit/<int:tid>",views.edit),
    path("update/<int:tid>",views.update),
    path("delete/<int:tid>",views.delete),
]

CRUD-7/app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    tid = models.AutoField(primary_key=True)
    task = models.CharField(max_length=20)
    time = models.TimeField()
    status = models.BooleanField('Done',default=False)
    def __str__(self):
        return self.task
    class Meta:
        db_table = 'task'

CRUD-7/app/forms.py
from django import forms 
from .models import Task
class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

CRUD-7/app/views.py
from django.shortcuts import render, redirect
from .forms import TaskForm
from .models import Task
# Create your views here.
def home(request):
    return render(request, 'home.html')

def task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = TaskForm()
    return render(request, 'index.html',{'form':form})

def show(request):
    tasks = Task.objects.order_by('time')
    return render(request, 'show.html',{'tasks':tasks})

def edit(request, tid):
    task = Task.objects.get(tid=tid)
    return render(request, 'edit.html',{'task':task})

def update(request, tid):
    task = Task.objects.get(tid=tid)
    form = TaskForm(request.POST, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html', {'task':task})

def delete(request, tid):
    task = Task.objects.get(tid=tid)
    task.delete()
    return redirect('/show')

CRUD-7/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Task Management System</title>
    </head>
    <body>
        <form method="post" class="post-form" action="/update/{{task.tid}}">
            {% csrf_token %}
            <div class="container">
                <h2>Task Details : </h2>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Enter Task : </h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task ID : </label>
                    <div class="col-sm-4">
                        <input type="hidden" name="tid" id="id_tid" value="{{ task.tid }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task : </label>
                    <div class="col-sm-4">
                        <input type="text" name="task" id="id_task" value="{{ task.task }}" maxlength="40" required/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task Time : </label>
                    <div class="col-sm-4">
                        <input type="time" name="time" id="id_time" value="{{ task.time }}" required/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task Status : </label>
                    <div class="col-sm-4">
                        <input type="checkbox" name="status" id="id_status" value="{{ task.status }}"/>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Update Task</button>
                        <button type="reset" class="btn btn-dark">Reset Task</button>
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

CRUD-7/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Task Management System</title>
    </head>
    <body>
        <form method="post" class="post-form">
            {% csrf_token %}
            <div class="container">
                <h2>Task Details : </h2>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <h3>Enter Task : </h3>
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task ID : </label>
                    <div class="col-sm-4">{{ form.tid }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task : </label>
                    <div class="col-sm-4">{{ form.task }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task Time : </label>
                    <div class="col-sm-4">{{ form.time }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label">Task Status : </label>
                    <div class="col-sm-4">{{ form.status }}</div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"></label>
                    <div class="col-sm-4">
                        <button type="submit" class="btn btn-success">Submit</button>
                        <button type="reset" class="btn btn-secondary">Reset</button>
                    </div>
                </div>
            </div>
        </form>
    </body>
</html>

CRUD-7/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Task Management System</title>
    </head>
    <body>
        <table class="table table-bordered table-striped table-sm table-dark">
            <thead class="thead-dark">
                <tr>
                    <th>Task ID</th>
                    <th>Task</th>
                    <th>Task Time</th>
                    <th>Task Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="tbody-dark">
                {% if not tasks %}
                    <tr>
                        <td colspan="5" class="text-center">No tasks found!</td>
                    </tr>
                {% else %}
                    {% for task in tasks %}
                    <tr>
                        <td>{{ task.tid }}</td>
                        <td>{{ task.task }}</td>
                        <td>{{ task.time }}</td>
                        <td>{{ task.status }}</td>
                        <td>
                            <a href="/update/{{task.tid}}" class="btn btn-primary">
                                <span class="glyphicon glyphicon-pencil">Edit Task</span>
                            </a>
                            <a href="/delete/{{task.tid}}" class="btn btn-danger">Delete Task</a>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <center>
            <a href="/task" class="btn btn-info">Add New Task</a>
        </center>
    </body>
</html>