CRUD-8/CRUD8/urls.py
from django.contrib import admin
from django.urls import path
from app import views
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",views.home),
    path("blog/",views.blog),
    path("show/",views.show),
    path("edit/<int:bid>",views.edit),
    path("update/<int:bid>",views.update),
    path("delete/<int:bid>",views.delete),
]

CRUD-8/app/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    bid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=80)
    content = models.CharField(max_length=100)
    author = models.CharField(max_length=60)
    date_published = models.DateField()
    class Meta:
        db_table = 'Blog'
    def __str__(self):
        return self.blog

CRUD-8/app/forms.py
from django import forms
from .models import Blog
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

CRUD-8/app/views.py
from django.shortcuts import render, redirect
from .models import Blog
from .forms import BlogForm
# Create your views here.
def home(request):
    return render(request, 'home.html')

def blog(request):
    if request.method  == 'POST':
        form = BlogForm(request.POST)
        try:
            if form.is_valid():
                form.save()
                return redirect('/show')
        except:
            pass
    else:
        form = BlogForm()
    return render(request, 'index.html',{'form':form})

def show(request):
    blogs = Blog.objects.order_by('-date_published')
    return render(request, 'show.html',{'blogs':blogs})

def edit(request, bid):
    blog = Blog.objects.get(bid=bid)
    return render(request, 'edit.html',{'blog':blog})

def update(request, bid):
    blog = Blog.objects.get(bid=bid)
    form = BlogForm(request.POST, instance=blog)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(request, 'edit.html',{'blog':blog})

def delete(request, bid):
    blog = Blog.objects.get(bid=bid)
    blog.delete()
    return redirect('/show')

CRUD-8/app/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Blog Management System</title>
</head>
<body>
    <form method="post" class="post-form" action="/update/{{blog.bid}}">
        {% csrf_token %}
        <div class="container">
            <h2>BLOGS</h2>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Blog Details : </h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog ID : </label>
                <div class="col-sm-4">
                    <input type="hidden" name="bid" id="id_bid" value="{{blog.bid}}"/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Title : </label>
                <div class="col-sm-4">
                    <input type="text" name="title" id="id_title" value="{{blog.title}}" maxlength="50" required/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Content : </label>
                <div class="col-sm-4">
                    <input type="text" name="content" id="id_content" value="{{blog.content}}" maxlength="100" required/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Author : </label>
                <div class="col-sm-4">
                    <input type="text" name="author" id="id_author" value="{{blog.author}}" maxlength="60" required/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Published Date : </label>
                <div class="col-sm-4">
                    <input type="date" name="date_published" id="id_date_published" value="{{blog.date_published}}" required/>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-info">Reset</button>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

CRUD-8/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Blog Management System</title>
</head>
<body>
    <form method="post" class="post-form">
        {% csrf_token %}
        <div class="container">
            <h2>BLOGS</h2>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <h3>Enter Blog Details : </h3>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog ID : </label>
                <div class="col-sm-4">{{ form.bid }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Title : </label>
                <div class="col-sm-4">{{ form.title }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Content : </label>
                <div class="col-sm-4">{{ form.content }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Author : </label>
                <div class="col-sm-4">{{ form.author }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">Blog Published Date : </label>
                <div class="col-sm-4">{{ form.date_published }}</div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label"></label>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-success">Submit</button>
                    <button type="reset" class="btn btn-info">Reset</button>
                </div>
            </div>
        </div>
    </form>
</body>
</html>

CRUD-8/app/templates/show.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <title>Task Management System</title>
    </head>
    <body>
        <table class="table table-bordered table-striped table-sm table-dark">
            <thead class="thead-dark">
                <tr>
                    <th>Blog ID</th>
                    <th>Title</th>
                    <th>Content</th>
                    <th>Author</th>
                    <th>Date Published</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="tbody-dark">
                {% if not blogs %}
                    <tr>
                        <td colspan="6" class="text-center">No blogs found!</td>
                    </tr>
                {% else %}
                    {% for blog in blogs %}
                    <tr>
                        <td>{{ blog.bid }}</td>
                        <td>{{ blog.title }}</td>
                        <td>{{ blog.content }}</td>
                        <td>{{ blog.author }}</td>
                        <td>{{ blog.date_published }}</td>
                        <td>
                            <a href="/update/{{blog.bid}}" class="btn btn-primary">
                                <span class="glyphicon glyphicon-pencil">Edit Blog</span>
                            </a>
                            <a href="/delete/{{blog.bid}}" class="btn btn-danger">Delete Blog</a>
                        </td>
                    </tr>
                    {% endfor %}
                {% endif %}
            </tbody>
        </table>
        <center>
            <a href="/blog" class="btn btn-info">Add New Blog</a>
        </center>
    </body>
</html>